name: "\U0001F41E Bug report"
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      placeholder: Reproduction
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Expected behavior
    validations:
      required: true  

   - type: textarea
    id: expected
    attributes:
      label: Actual behavior
      placeholder: Actual behavior
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version of libgit2
      description: |
       (release number or SHA1)
      render: shell-script

  - type: textarea
    id: operating-system
    attributes:
      label: Operating system(s) tested
      description: |
       (release number or SHA1)
